DROP TABLE IF EXISTS BUILDER_WEB_FORMS;
CREATE TABLE BUILDER_WEB_FORMS (
  BUILDER_FORM_ID int(11) unsigned NOT NULL auto_increment,
  FORM_NAME varchar(200) NOT NULL default '',
  FORM_ID varchar(50) default NULL,
  TABLE_ANCHOR varchar(200) default NULL,
  BUILDER_FIELD_NO int(11) unsigned default NULL,
  MODULE VARCHAR(50) DEFAULT '',
  IS_CUSTOM CHAR DEFAULT 'N',
  IS_ACTIVE CHAR DEFAULT 'Y',
  CAPTIVATE_SECTION_ID VARCHAR(255) DEFAULT NULL,
  DISPLAY_NAME varchar(255),
  ADD_MORE VARCHAR(10),
  PRIMARY KEY  (BUILDER_FORM_ID),
  KEY formId (FORM_ID),
  KEY BUILDER_FIELD_NO (BUILDER_FIELD_NO)
)  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS TAB_BUILDER_BACKUP;
CREATE TABLE TAB_BUILDER_BACKUP (
  BUILDER_FORM_ID int(11) unsigned NOT NULL auto_increment,
  FORM_NAME varchar(200) NOT NULL default '',
  FORM_ID varchar(50) default NULL,
  TABLE_ANCHOR varchar(200) default NULL,
  BUILDER_FIELD_NO int(11) unsigned default NULL,
  MODULE VARCHAR(50) DEFAULT '',
  PRIMARY KEY  (BUILDER_FORM_ID),
  KEY formId (FORM_ID),
  KEY BUILDER_FIELD_NO (BUILDER_FIELD_NO)
)  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS FORM_BUILDER_TAB_LOGS;
CREATE TABLE FORM_BUILDER_TAB_LOGS
(
 ID		 INT(11) PRIMARY KEY AUTO_INCREMENT,
 BUILDER_FORM_ID INT(11),
 TAB_ID		 VARCHAR(50),
 TAB_NAME	 VARCHAR(255),
 MODULE		 VARCHAR(50),
 ACTION		 VARCHAR(20),
 DESCRIPTION	 TEXT,
 CHANGE_DATE	 datetime,
 USER_NO	 INT(11),
 IP_ADDRESS	 VARCHAR(20)
)  DEFAULT CHARSET=utf8;