DROP TABLE IF EXISTS BUILDER_WEB_FORMS;
CREATE TABLE BUILDER_WEB_FORMS (
  BUILDER_FORM_ID int(11) unsigned NOT NULL auto_increment,
  FORM_NAME varchar(200) NOT NULL default '',
  FORM_ID varchar(50) default NULL,
  TABLE_ANCHOR varchar(200) default NULL,
  BUILDER_FIELD_NO int(11) unsigned default NULL,
  MODULE VARCHAR(50) DEFAULT '',
  IS_CUSTOM CHAR DEFAULT 'N',
  IS_ACTIVE CHAR DEFAULT 'Y',
  CAPTIVATE_SECTION_ID VARCHAR(255) DEFAULT NULL,
  DISPLAY_NAME varchar(255),
  ADD_MORE VARCHAR(10),
  PRIMARY KEY  (BUILDER_FORM_ID),
  KEY formId (FORM_ID),
  KEY BUILDER_FIELD_NO (BUILDER_FIELD_NO)
)  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS TAB_BUILDER_BACKUP;
CREATE TABLE TAB_BUILDER_BACKUP (
  BUILDER_FORM_ID int(11) unsigned NOT NULL auto_increment,
  FORM_NAME varchar(200) NOT NULL default '',
  FORM_ID varchar(50) default NULL,
  TABLE_ANCHOR varchar(200) default NULL,
  BUILDER_FIELD_NO int(11) unsigned default NULL,
  MODULE VARCHAR(50) DEFAULT '',
  PRIMARY KEY  (BUILDER_FORM_ID),
  KEY formId (FORM_ID),
  KEY BUILDER_FIELD_NO (BUILDER_FIELD_NO)
)  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS FORM_BUILDER_TAB_LOGS;
CREATE TABLE FORM_BUILDER_TAB_LOGS
(
 ID		 INT(11) PRIMARY KEY AUTO_INCREMENT,
 BUILDER_FORM_ID INT(11),
 TAB_ID		 VARCHAR(50),
 TAB_NAME	 VARCHAR(255),
 MODULE		 VARCHAR(50),
 ACTION		 VARCHAR(20),
 DESCRIPTION	 TEXT,
 CHANGE_DATE	 datetime,
 USER_NO	 INT(11),
 IP_ADDRESS	 VARCHAR(20)
)  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS FIM_BUILDER_MASTER_DATA;
CREATE TABLE FIM_BUILDER_MASTER_DATA (
  ID int(11) NOT NULL auto_increment,
  FIELD_ID int(11) default '0',
  FIELD_NAME varchar(255) default '',
  OPTION_ID int(11) NOT NULL default '0',
  OPTION_VALUE varchar(255) NOT NULL default '',
  TABLE_ANCHOR varchar(64) default NULL,
  IS_ACTIVE char(1) NOT NULL default 'N',
  DEPENDENT_VALUE VARCHAR(155) DEFAULT NULL,
  ORDER_NO int(11) NOT NULL default '0',
  PRIMARY KEY  (ID),
  KEY OPTION_ID_IDX (OPTION_ID)
)  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS TABULAR_SECTION_DISPLAY_COLUMN;
CREATE TABLE TABULAR_SECTION_DISPLAY_COLUMN (DISPLAY_ID int(11) unsigned NOT NULL auto_increment,
DISPLAY_NAME TEXT default NULL,
DISPLAY_VALUE varchar(200) default NULL,
MODULE_ID int(2) default NULL,
IS_SELECTED int(1) default NULL,
ORDER_SEQUENCE int(11) DEFAULT null,
USER_NO INT(11) DEFAULT 0,
IS_ACTIVE VARCHAR(5) DEFAULT 'yes',
FIELD_NAME VARCHAR(255),
IS_PII_ENABLED varchar(5) DEFAULT 'false',
TABLE_NAME VARCHAR(255),
MAIN_TABLE_NAME VARCHAR(255),
PRIMARY KEY  (DISPLAY_ID),
KEY moduleId (MODULE_ID),
KEY orderSequence (ORDER_SEQUENCE)
)  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CONFIGURE_TABULAR_FIELDS;
CREATE TABLE CONFIGURE_TABULAR_FIELDS(
MAP_ID int(11) unsigned NOT NULL auto_increment,
TABLE_ANCHOR varchar(50),
FIELDS text,
ORDER_NO int(11),
IS_ACTIVE CHAR(1) default 'Y',
PRIMARY KEY (MAP_ID)
) DEFAULT CHARSET=utf8;